# Generated by Django 3.1.2 on 2020-10-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20201003_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('EN', 'Enviado'), ('RV', 'Revisado'), ('RE', 'Reprovado'), ('AP', 'Aprovado')], default='EN', max_length=2),
        ),
    ]
