# Generated by Django 3.1.2 on 2020-10-06 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20201006_0017'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formpayment',
            options={'verbose_name': 'Type Payment', 'verbose_name_plural': 'Types Payments'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'verbose_name': 'Status', 'verbose_name_plural': 'Status'},
        ),
    ]
