# Generated by Django 3.1.2 on 2020-10-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='complement',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='neighborhood',
        ),
        migrations.RemoveField(
            model_name='address',
            name='number',
        ),
        migrations.RemoveField(
            model_name='address',
            name='place',
        ),
        migrations.AddField(
            model_name='profile',
            name='adress_city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='adress_complement',
            field=models.CharField(blank=True, max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='adress_country',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='adress_neighborhood',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='adress_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='adress_place',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
